### PR TITLE
Side bar closes when item is selected

### PR DESCRIPTION
**Pull request by midyan**
Hi,

I have added a global variable and function to manage the state of the sidebar.
Please, test it out to see if everything is working correctly.

### CODE REVIEW

**Comment by MilesGG** [comment]
The [build is failing](https://travis-ci.org/Teracycle/teracycle-pool/builds/250052323)(I think it's because there isn't a `.travis.yml`) but so is the [current master](https://travis-ci.org/Teracycle/teracycle-pool/builds/250052323) for the same reason, so I see no reason not to merge.

**Comment by JamesKegel** [comment]
The travis.yml is in there because I intended to write some tests but fell asleep and then forgot to take it out after. I can remove it until I write tests

**Comment by JamesKegel** [comment]
Code is on the main site now, it works for the most part. Can anybody verify this issue I'm having?
Chrome Browser on ChromeOS
http://teracycle.net
click menu hamburger
click "Getting Started" (nav stays open, page loads)
click "Home" (nav closes, home loads)
click menu hamburger
click "market" (nav stays open, page loads)

It is working on some buttons, but not on others.

**Comment by midyan** [comment]
Yep, just saw that. #2 Should fix it.

**Pull request merged**
